# =============================================================================
# CORE MODULE - Shared utilities, theme, project management
# =============================================================================
set(CORE_SOURCES
    core/theme.cpp
    core/theme.h
    core/theme_manager.cpp
    core/theme_manager.h
    core/project.cpp
    core/project.h
    core/recent_projects.cpp
    core/recent_projects.h
    core/recent_workspaces.cpp
    core/recent_workspaces.h
    core/settings_dialog.cpp
    core/settings_dialog.h
    core/config_manager.cpp
    core/config_manager.h
    core/sync_manager.h
    core/eco_types.h
    core/library_index.cpp
    core/library_index.h
    core/assignment_validator.cpp
    core/assignment_validator.h
    core/net_class.cpp
    core/net_class.h
    core/simulation_manager.cpp
    core/simulation_manager.h
    core/diagnostics/debugger.cpp
    core/diagnostics/debugger.h
    core/bom_manager.cpp
    core/bom_manager.h
    core/remote_display_server.cpp
    core/remote_display_server.h
    core/plugins/plugin_manager.cpp
    core/plugins/plugin_manager.h
    core/plugins/plugin_catalog_client.cpp
    core/plugins/plugin_catalog_client.h
    core/plugins/plugin_package_installer.cpp
    core/plugins/plugin_package_installer.h
    core/ui/selection_filter_widget.cpp
    core/ui/selection_filter_widget.h
    core/ui/command_palette.cpp
    core/ui/command_palette.h
)

if(VIOSPICE_ENABLE_PYTHON)
    list(APPEND CORE_SOURCES
        core/flux_python.cpp
        core/flux_python.h
    )
endif()

# =============================================================================
# SYMBOLS MODULE - Symbol definition and library
# =============================================================================
set(SYMBOLS_SOURCES
    symbols/models/symbol_primitive.cpp
    symbols/models/symbol_primitive.h
    symbols/models/symbol_definition.cpp
    symbols/models/symbol_definition.h
    symbols/items/symbol_primitive_item.cpp
    symbols/items/symbol_primitive_item.h
    symbols/analysis/symbol_engine.cpp
    symbols/analysis/symbol_engine.h
    symbols/symbol_library.cpp
    symbols/symbol_library.h
    symbols/symbol_editor.cpp
    symbols/symbol_editor.h
    symbols/symbol_editor_view.cpp
    symbols/symbol_editor_view.h
    symbols/symbol_commands.cpp
    symbols/symbol_commands.h
    symbols/pin_table_dialog.cpp
    symbols/pin_table_dialog.h
    symbols/pin_modes_dialog.cpp
    symbols/pin_modes_dialog.h
    symbols/kicad_symbol_importer.cpp
    symbols/kicad_symbol_importer.h
    symbols/ltspice_symbol_importer.cpp
    symbols/ltspice_symbol_importer.h
    symbols/ui/symbol_preview_widget.cpp
    symbols/ui/symbol_preview_widget.h
    symbols/ui/ai_datasheet_import_dialog.cpp
    symbols/ui/ai_datasheet_import_dialog.h
)

# =============================================================================
# SCHEMATIC MODULE - Schematic editor, items, tools
# =============================================================================
set(SCHEMATIC_SOURCES
    # Editor (split across multiple files for maintainability)
    schematic/editor/schematic_editor.cpp
    schematic/editor/schematic_editor_ui.cpp
    schematic/editor/schematic_editor_theme.cpp
    schematic/editor/schematic_editor_actions.cpp
    schematic/editor/schematic_editor_file.cpp
    schematic/editor/schematic_editor_export.cpp
    schematic/editor/spice_directive_classifier.cpp
    schematic/editor/spice_directive_classifier.h
    schematic/editor/schematic_editor.h
    schematic/ui/schematic_components_widget.cpp
    schematic/ui/schematic_components_widget.h
    schematic/ui/library_browser_dialog.cpp
    schematic/ui/library_browser_dialog.h
    schematic/dialogs/component_properties_dialog.cpp
    schematic/dialogs/component_properties_dialog.h
    schematic/dialogs/generic_symbol_properties_dialog.cpp
    schematic/dialogs/generic_symbol_properties_dialog.h
    schematic/dialogs/smart_properties_dialog.cpp
    schematic/dialogs/smart_properties_dialog.h
    schematic/dialogs/symbol_field_editor_dialog.cpp
    schematic/dialogs/symbol_field_editor_dialog.h
    schematic/dialogs/bus_aliases_dialog.cpp
    schematic/dialogs/bus_aliases_dialog.h
    schematic/dialogs/bus_properties_dialog.cpp
    schematic/dialogs/bus_properties_dialog.h
    schematic/dialogs/find_replace_dialog.cpp
    schematic/dialogs/find_replace_dialog.h
    schematic/dialogs/net_label_properties_dialog.cpp
    schematic/dialogs/net_label_properties_dialog.h
    schematic/dialogs/erc_rules_dialog.cpp
    schematic/dialogs/erc_rules_dialog.h
    schematic/dialogs/title_block_dialog.cpp
    schematic/dialogs/title_block_dialog.h
    schematic/dialogs/visual_spice_mapper_dialog.cpp
    schematic/dialogs/visual_spice_mapper_dialog.h
    schematic/dialogs/wire_properties_dialog.cpp
    schematic/dialogs/wire_properties_dialog.h
    schematic/dialogs/passive_properties_dialog.cpp
    schematic/dialogs/passive_properties_dialog.h
    schematic/dialogs/passive_model_properties_dialog.cpp
    schematic/dialogs/passive_model_properties_dialog.h
    schematic/dialogs/passive_model_picker_dialog.cpp
    schematic/dialogs/passive_model_picker_dialog.h
    schematic/dialogs/schematic_text_properties_dialog.cpp
    schematic/dialogs/schematic_text_properties_dialog.h
    schematic/dialogs/schematic_diff_dialog.cpp
    schematic/dialogs/schematic_diff_dialog.h
    schematic/dialogs/sheet_properties_dialog.cpp
    schematic/dialogs/sheet_properties_dialog.h
    schematic/dialogs/signal_generator_properties_dialog.cpp
    schematic/dialogs/signal_generator_properties_dialog.h
    schematic/dialogs/logic_analyzer_properties_dialog.cpp
    schematic/dialogs/logic_analyzer_properties_dialog.h
    schematic/dialogs/tuning_slider_properties_dialog.cpp
    schematic/dialogs/tuning_slider_properties_dialog.h
    schematic/dialogs/led_properties_dialog.cpp
    schematic/dialogs/led_properties_dialog.h
    schematic/dialogs/switch_properties_dialog.cpp
    schematic/dialogs/switch_properties_dialog.h
    schematic/dialogs/csw_properties_dialog.cpp
    schematic/dialogs/csw_properties_dialog.h
    schematic/dialogs/cccs_properties_dialog.cpp
    schematic/dialogs/cccs_properties_dialog.h
    schematic/dialogs/ccvs_properties_dialog.cpp
    schematic/dialogs/ccvs_properties_dialog.h
    schematic/dialogs/transmission_line_properties_dialog.cpp
    schematic/dialogs/transmission_line_properties_dialog.h
    schematic/dialogs/vcvs_properties_dialog.cpp
    schematic/dialogs/vcvs_properties_dialog.h
    schematic/dialogs/diode_model_picker_dialog.cpp
    schematic/dialogs/diode_model_picker_dialog.h
    schematic/dialogs/diode_properties_dialog.cpp
    schematic/dialogs/diode_properties_dialog.h
    schematic/dialogs/bjt_model_picker_dialog.cpp
    schematic/dialogs/bjt_model_picker_dialog.h
    schematic/dialogs/bjt_properties_dialog.cpp
    schematic/dialogs/bjt_properties_dialog.h
    schematic/dialogs/mos_model_picker_dialog.cpp
    schematic/dialogs/mos_model_picker_dialog.h
    schematic/dialogs/mos_properties_dialog.cpp
    schematic/dialogs/mos_properties_dialog.h
    schematic/dialogs/mesfet_properties_dialog.cpp
    schematic/dialogs/mesfet_properties_dialog.h
    schematic/dialogs/jfet_model_picker_dialog.cpp
    schematic/dialogs/jfet_model_picker_dialog.h
    schematic/dialogs/jfet_properties_dialog.cpp
    schematic/dialogs/jfet_properties_dialog.h
    schematic/dialogs/voltage_controlled_switch_dialog.cpp
    schematic/dialogs/voltage_controlled_switch_dialog.h
    schematic/dialogs/behavioral_current_source_dialog.cpp
    schematic/dialogs/behavioral_current_source_dialog.h
    schematic/dialogs/current_source_properties_dialog.cpp
    schematic/dialogs/current_source_properties_dialog.h
    schematic/dialogs/current_source_ltspice_dialog.cpp
    schematic/dialogs/current_source_ltspice_dialog.h
    schematic/dialogs/oscilloscope_properties_dialog.cpp
    schematic/dialogs/oscilloscope_properties_dialog.h
    schematic/dialogs/voltage_source_properties_dialog.cpp
    schematic/dialogs/voltage_source_properties_dialog.h
    schematic/dialogs/voltage_source_ltspice_dialog.cpp
    schematic/dialogs/voltage_source_ltspice_dialog.h
    schematic/dialogs/voltage_source_custom_waveform_dialog.cpp
    schematic/dialogs/voltage_source_custom_waveform_dialog.h
    schematic/dialogs/spice_directive_dialog.cpp
    schematic/dialogs/spice_directive_dialog.h
    schematic/dialogs/spice_subcircuit_import_dialog.cpp
    schematic/dialogs/spice_subcircuit_import_dialog.h
    schematic/dialogs/subcircuit_picker_dialog.cpp
    schematic/dialogs/subcircuit_picker_dialog.h
    schematic/dialogs/spice_mean_dialog.cpp
    schematic/dialogs/spice_mean_dialog.h
    schematic/dialogs/spice_step_dialog.cpp
    schematic/dialogs/spice_step_dialog.h
    schematic/dialogs/simulation_debugger_dialog.cpp
    schematic/dialogs/simulation_debugger_dialog.h
    schematic/dialogs/power_nets_manager_dialog.cpp
    schematic/dialogs/power_nets_manager_dialog.h
    schematic/editor/schematic_view.cpp
    schematic/editor/schematic_view.h
    schematic/editor/schematic_commands.cpp
    schematic/editor/schematic_commands.h
    schematic/editor/schematic_menu_registry.cpp
    schematic/editor/schematic_menu_registry.h
    schematic/editor/schematic_api.cpp
    schematic/editor/schematic_api.h
    
    # Items
    schematic/items/schematic_item.cpp
    schematic/items/schematic_item.h
    schematic/items/generic_component_item.cpp
    schematic/items/generic_component_item.h
    schematic/items/resistor_item.cpp
    schematic/items/resistor_item.h
    schematic/items/potentiometer_item.cpp
    schematic/items/potentiometer_item.h
    schematic/items/capacitor_item.cpp
    schematic/items/capacitor_item.h
    schematic/items/inductor_item.cpp
    schematic/items/inductor_item.h
    schematic/items/diode_item.cpp
    schematic/items/diode_item.h
    schematic/items/transistor_item.cpp
    schematic/items/transistor_item.h
    schematic/items/ic_item.cpp
    schematic/items/ic_item.h
    schematic/items/transformer_item.cpp
    schematic/items/transformer_item.h
    schematic/items/wire_item.cpp
    schematic/items/wire_item.h
    schematic/items/switch_item.h
    schematic/items/switch_item.cpp
    schematic/items/voltage_controlled_switch_item.h
    schematic/items/voltage_controlled_switch_item.cpp
    schematic/items/current_source_item.h
    schematic/items/current_source_item.cpp
    schematic/items/behavioral_current_source_item.h
    schematic/items/behavioral_current_source_item.cpp
    schematic/items/push_button_item.h
    schematic/items/push_button_item.cpp
    schematic/items/led_item.h
    schematic/items/led_item.cpp
    schematic/items/blinking_led_item.h
    schematic/items/blinking_led_item.cpp
    schematic/items/smart_signal_item.h
    schematic/items/smart_signal_item.cpp
    schematic/items/simulation_overlay_item.h
    schematic/items/signal_generator_item.cpp
    schematic/items/signal_generator_item.h
    schematic/items/logic_analyzer_item.cpp
    schematic/items/logic_analyzer_item.h
    schematic/items/oscilloscope_item.cpp
    schematic/items/oscilloscope_item.h
    schematic/items/tuning_slider_item.cpp
    schematic/items/tuning_slider_item.h
    schematic/items/tuning_slider_symbol_item.cpp
    schematic/items/tuning_slider_symbol_item.h
    schematic/items/instrument_probe_item.cpp
    schematic/items/instrument_probe_item.h
    schematic/items/schematic_page_item.cpp
    schematic/items/schematic_page_item.h
    schematic/items/power_item.cpp
    schematic/items/power_item.h
    schematic/items/voltage_source_item.cpp
    schematic/items/voltage_source_item.h
    schematic/items/hierarchical_port_item.cpp
    schematic/items/hierarchical_port_item.h
    schematic/items/erc_marker_item.cpp
    schematic/items/erc_marker_item.h
    schematic/items/schematic_sheet_item.cpp
    schematic/items/schematic_spice_directive_item.cpp
    schematic/items/schematic_spice_directive_item.h
    schematic/items/schematic_waveform_marker.cpp
    schematic/items/schematic_waveform_marker.h
    schematic/items/schematic_sheet_item.h
    schematic/items/schematic_shape_item.cpp
    schematic/items/schematic_shape_item.h
    schematic/items/schematic_text_item.cpp
    schematic/items/schematic_text_item.h
    schematic/items/no_connect_item.cpp
    schematic/items/no_connect_item.h
    schematic/items/bus_item.cpp
    schematic/items/bus_item.h
    schematic/items/bus_entry_item.cpp
    schematic/items/bus_entry_item.h
    schematic/items/net_label_item.cpp
    schematic/items/net_label_item.h
    schematic/items/air_wire_item.cpp
    schematic/items/air_wire_item.h
    schematic/items/schematic_hint_item.cpp
    schematic/items/schematic_hint_item.h
    
    # Tools
    schematic/tools/schematic_tool.cpp
    schematic/tools/schematic_tool.h
    schematic/tools/schematic_tool_registry.cpp
    schematic/tools/schematic_tool_registry.h
    schematic/tools/schematic_tool_registry_builtin.cpp
    schematic/tools/schematic_tool_registry_builtin.h
    schematic/tools/schematic_select_tool.cpp
    schematic/tools/schematic_select_tool.h
    schematic/tools/schematic_component_tool.cpp
    schematic/tools/schematic_component_tool.h
    schematic/tools/schematic_wire_tool.cpp
    schematic/tools/schematic_wire_tool.h
    schematic/tools/schematic_zoom_area_tool.cpp
    schematic/tools/schematic_zoom_area_tool.h
    schematic/tools/schematic_scissors_tool.cpp
    schematic/tools/schematic_scissors_tool.h
    schematic/tools/schematic_shape_tool.cpp
    schematic/tools/schematic_shape_tool.h
    schematic/tools/schematic_text_tool.cpp
    schematic/tools/schematic_text_tool.h
    schematic/tools/schematic_no_connect_tool.cpp
    schematic/tools/schematic_no_connect_tool.h
    schematic/tools/schematic_bus_tool.cpp
    schematic/tools/schematic_bus_tool.h
    schematic/tools/schematic_bus_entry_tool.cpp
    schematic/tools/schematic_bus_entry_tool.h
    schematic/tools/schematic_net_label_tool.cpp
    schematic/tools/schematic_net_label_tool.h
    schematic/tools/schematic_hierarchical_port_tool.cpp
    schematic/tools/schematic_hierarchical_port_tool.h
    schematic/tools/schematic_sheet_tool.cpp
    schematic/tools/schematic_probe_tool.cpp
    schematic/tools/schematic_probe_tool.h
    schematic/tools/schematic_spice_directive_tool.cpp
    schematic/tools/schematic_spice_directive_tool.h
    schematic/tools/schematic_sheet_tool.h
    schematic/tools/schematic_wire_utils.cpp
    schematic/tools/schematic_wire_utils.h
    
    # I/O
    schematic/io/schematic_file_io.cpp
    schematic/io/schematic_file_io.h
    schematic/io/ltspice_asc_importer.cpp
    schematic/io/ltspice_asc_importer.h
    schematic/io/netlist_generator.cpp
    schematic/io/netlist_generator.h
    schematic/io/spice_netlist_parser.cpp
    schematic/io/spice_netlist_parser.h
    schematic/io/netlist_to_schematic.cpp
    schematic/io/netlist_to_schematic.h
    
    # Analysis
    schematic/analysis/schematic_erc.cpp
    schematic/analysis/schematic_erc.h
    schematic/analysis/schematic_erc_rules.cpp
    schematic/analysis/schematic_erc_rules.h
    schematic/analysis/schematic_layout_optimizer.cpp
    schematic/analysis/schematic_layout_optimizer.h
    schematic/analysis/schematic_connectivity.cpp
    schematic/analysis/schematic_connectivity.h
    schematic/analysis/wire_router.cpp
    schematic/analysis/wire_router.h
    schematic/analysis/spice_netlist_generator.cpp
    schematic/analysis/spice_netlist_generator.h
    schematic/analysis/net_manager.cpp
    schematic/analysis/net_manager.h
    schematic/analysis/fft_analyzer.cpp
    schematic/analysis/fft_analyzer.h
    schematic/analysis/schematic_diff_engine.cpp
    schematic/analysis/schematic_diff_engine.h
    
    # UI Dialogs
    schematic/ui/bom_dialog.cpp
    schematic/ui/bom_dialog.h
    schematic/ui/erc_diagnostics_panel.cpp
    schematic/ui/erc_diagnostics_panel.h
    schematic/ui/flux_code_editor.cpp
    schematic/ui/flux_code_editor.h
    schematic/ui/flux_completer.cpp
    schematic/ui/flux_completer.h
    schematic/ui/flux_script_panel.cpp
    schematic/ui/flux_script_panel.h
    schematic/ui/netlist_editor.cpp
    schematic/ui/netlist_editor.h
    schematic/ui/spice_highlighter.cpp
    schematic/ui/spice_highlighter.h
    schematic/ui/logic_editor_panel.cpp
    schematic/ui/logic_editor_panel.h
    schematic/ui/mini_scope_widget.cpp
    schematic/ui/mini_scope_widget.h
    schematic/ui/model_browser_widget.cpp
    schematic/ui/model_browser_widget.h
    schematic/ui/visual_pin_mapper.cpp
    schematic/ui/visual_pin_mapper.h
    schematic/ui/schematic_hierarchy_panel.cpp
    schematic/ui/schematic_hierarchy_panel.h
    schematic/ui/simulation_panel.cpp
    schematic/ui/simulation_panel.h
    schematic/ui/simulation_log_dialog.cpp
    schematic/ui/simulation_log_dialog.h
    ui/waveform_viewer.cpp
    ui/waveform_viewer.h
    ui/analysis_dialog.cpp
    ui/analysis_dialog.h
    ui/measurement_dialog.cpp
    ui/measurement_dialog.h
    ui/fft_analyzer.cpp
    ui/fft_analyzer.h
    ui/waveform_expression_dialog.cpp
    ui/waveform_expression_dialog.h
    schematic/ui/simulation_setup_dialog.cpp
    schematic/ui/simulation_setup_dialog.h
    schematic/ui/virtual_instruments.cpp
    schematic/ui/logic_analyzer_window.cpp
    schematic/ui/logic_analyzer_window.h
    schematic/ui/oscilloscope_window.cpp
    schematic/ui/oscilloscope_window.h
    schematic/ui/virtual_instruments.cpp
    schematic/ui/virtual_instruments.h
    schematic/ui/schematic_diff_viewer.cpp
    schematic/ui/schematic_diff_viewer.h
    schematic/analysis/schematic_annotator.cpp
    schematic/analysis/schematic_annotator.h
    
    # Factories
    schematic/factories/schematic_item_factory.cpp
    schematic/factories/schematic_item_factory.h
    schematic/factories/schematic_item_registry.cpp
    schematic/factories/schematic_item_registry.h
    
    # Primitives
    schematic/schematic_primitives.cpp
    schematic/schematic_primitives.h
)

if(NOT VIOSPICE_ENABLE_PYTHON)
    list(REMOVE_ITEM SCHEMATIC_SOURCES
        schematic/ui/logic_editor_panel.cpp
        schematic/ui/logic_editor_panel.h
    )
endif()

# =============================================================================
# UI MODULE - Project manager and shared UI
# =============================================================================
set(UI_SOURCES
    ui/project_manager.cpp
    ui/csv_viewer.cpp
    ui/csv_viewer.h
    ui/help_window.cpp
    ui/help_window.h
    ui/developer_help_window.cpp
    ui/spice_model_architect.cpp
    ui/spice_model_architect.h
    ui/project_explorer_widget.cpp
    ui/project_explorer_widget.h
    ui/image_preview_panel.cpp
    ui/image_preview_panel.h
    ui/git_backend.cpp
    ui/git_backend.h
    ui/source_control_manager.cpp
    ui/source_control_manager.h
    ui/source_control_panel.cpp
    ui/source_control_panel.h
    ui/diff_viewer_dialog.cpp
    ui/diff_viewer_dialog.h
    ui/branch_dialog.cpp
    ui/branch_dialog.h

    core/ui/project_audit_dialog.cpp
    ui/calculator_dialog.cpp
    ui/calculator_dialog.h
    ui/spice_model_manager_dialog.cpp
    ui/spice_model_manager_dialog.h
    ui/plugin_manager_dialog.cpp
    ui/plugin_manager_dialog.h
    ui/property_editor.cpp
    ui/property_editor.h
    ui/spice_model_list_model.cpp
    ui/spice_model_list_model.h
    ui/symbol_list_model.cpp
    ui/symbol_list_model.h
    ui/splash_screen.cpp
    ui/splash_screen.h
    core/ui/color_button.cpp
    core/ui/color_button.h
    core/ui/text_properties_dialog.cpp
    core/ui/text_properties_dialog.h
)

# =============================================================================
